command:
  - python
  - start.py

env:
  - name: DATABRICKS_HOST
    value: "https://fe-vm-vdm-serverless-nmmvdg.cloud.databricks.com"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "ed6b19e7cf9a48aa"
  - name: DATABRICKS_CATALOG
    value: "danone_uc"
  - name: DATABRICKS_SCHEMA
    value: "digital_twin"
  - name: SECRET_SCOPE
    value: "dairyflow-secrets"
  - name: SECRET_KEY
    value: "databricks-pat"
